-- Mini ATM - 5 beginner-friendly database tables

create table customers (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text,
    created_at timestamptz default now()
);

create table accounts (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id) on delete cascade,
    account_number text unique not null,
    account_type text not null default 'Savings',
    balance numeric(12,2) not null default 0,
    created_at timestamptz default now()
);

create table atm_cards (
    id bigint generated by default as identity primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    card_number text unique not null,
    pin_hash text not null,
    is_active boolean not null default true,
    created_at timestamptz default now()
);

create table transactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    transaction_type text not null,
    amount numeric(12,2) not null,
    created_at timestamptz default now()
);

create table atm_sessions (
    id bigint generated by default as identity primary key,
    card_id bigint not null references atm_cards(id) on delete cascade,
    login_status text not null,
    created_at timestamptz default now()
);
